apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloudwatch-insights.frontend.fullname" . }}
  labels:
    {{- include "cloudwatch-insights.frontend.selectorLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "cloudwatch-insights.frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cloudwatch-insights.frontend.selectorLabels" . | nindent 8 }}
      {{- with .Values.frontend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: BACKEND_SERVICE_HOST
              value: {{ include "cloudwatch-insights.backend.fullname" . }}
            - name: BACKEND_SERVICE_PORT
              value: {{ .Values.backend.service.port | quote }}
          {{- with .Values.frontend.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.frontend.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
